/* Automatically generated by './build/bin/build-entry.js' */

import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Header from '../packages/header/index.js';
import Aside from '../packages/aside/index.js';
import Footer from '../packages/footer/index.js';
import Main from '../packages/main/index.js';
import Container from '../packages/container/index.js';
import Icon from '../packages/icon/index.js';
import Button from '../packages/button/index.js';
import ButtonGroup from '../packages/button-group/index.js';
import Link from '../packages/link/index.js';
import Radio from '../packages/radio/index.js';
import RadioGroup from '../packages/radio-group/index.js';
import RadioButton from '../packages/radio-button/index.js';
import Checkbox from '../packages/checkbox/index.js';
import CheckboxGroup from '../packages/checkbox-group/index.js';
import CheckboxButton from '../packages/checkbox-button/index.js';
import Input from '../packages/input/index.js';
import From from '../packages/form/index.js';
import FromItem from '../packages/form-item/index.js';

const components = [
    Row,
    Col,
    Header,
    Aside,
    Footer,
    Main,
    Container,
    Icon,
    Button,
    ButtonGroup,
    Link,
    Radio,
    RadioGroup,
    RadioButton,
    Checkbox,
    CheckboxGroup,
    CheckboxButton,
    Input,
    From,
    FromItem,
];

const install = function(Vue, opts = {}) {
    components.forEach(component => {
        Vue.component(component.name, component);
    });

    Vue.prototype.$YX = {
        size: opts.size || '',
    };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

export default {
    version: '0.1.0',
    install,
};
